name: maven-release-snapshot.yml

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Executar Maven Release (main/master)
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/jjjunior/pom-parent-jstack-core.git
          mvn -B release:prepare release:perform \
            -DscmCommentPrefix="[release] " \
            -Dscm.url=scm:git:https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/jjjunior/pom-parent-jstack-core.git \
            -Darguments="-DaltDeploymentRepository=github::default::https://maven.pkg.github.com/jjjunior/pom-parent-jstack-core"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy SNAPSHOT (outras branches)
        if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master'
        run: mvn deploy -B -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/jjjunior/pom-parent-jstack-core
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
