name: maven-deploy.yml
# Descrição: Este arquivo de workflow do GitHub Actions é responsável por fazer o deploy de um projeto Java utilizando Maven.
on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build e Deploy com Maven
        run: mvn deploy -B
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}